# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_garage-crm-tawny.vercel.app	FALSE	/	TRUE	1784094076	crm_session	eyJ1aWQiOiJjbXJhbzV4eWcwMDAxMTMxdW44eWFmaWI3Iiwicm9sZSI6InN0YWZmIiwibmFtZSI6ImNhcmkiLCJleHAiOjE3ODQwOTQwNzU5NTV9.XH3_POvBL_m6tvjxIgK41Vi7S6n7O_ZZ4gZfhDD0j_4
